### ISSUE TITLE
Les tests ont une dépendance vers l'API externe du référentiel

### ISSUE THREAD

**Issue by octo-topi** [1024pix/pix-db-replication#85]
[Les tests d'import de données ](http://github.com/1024pix/pix-db-replication/blob/71133c070f28f8e368159b21183014b24cb803c0/test/integration/steps_test.js#L483-L483) sont faits sur une API externe (Airtable).

En mockant cette API, on aurait:
- des tests plus rapide
- des tests déterministes
- des tests mieux sécurisés

On peut en profiter pour migrer sur l'API LCMS

**Comment by francois2metz** [comment]
Les données du référentiel sont récupéré depuis LCMS https://github.com/1024pix/pix-db-replication/pull/103
