### ISSUE TITLE
La table knowledge-element-snapshots n'est pas répliquée par dump lorsque la réplication incrémentale est désactivée

### ISSUE THREAD

**Issue by octo-topi** [1024pix/pix-db-replication#94]
Suite à https://github.com/1024pix/pix-db-replication/pull/90

**Comment by jonathanperret** [comment]
#92 n'est qu'un refactoring de la fonctionnalité de réplication incrémentale existante, c'est plutôt #90 qui passe cette table en réplication incrémentale.

**Comment by francois2metz** [comment]
Corrigé par https://github.com/1024pix/pix-db-replication/pull/97
